# Generated by Django 6.0.4 on 2026-04-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, unique=True)),
                (
                    "title_en",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
    ]
